import {
  Animal,
  SymptomReport,
  DiseaseCase,
  Vaccination,
  Treatment,
  LabSample,
  Outbreak,
  Advisory,
  NotificationItem,
  VetServiceLocation,
  User,
} from '../types';

export const FALLBACK_USERS: Record<string, User> = {
  FARMER: {
    id: 'usr-farmer-01',
    name: 'Ramesh Tukaram Patil',
    email: 'farmer@pashusetu.gov.in',
    mobile: '9876543210',
    role: 'FARMER',
    language: 'mr',
    farmerProfile: {
      id: 'fp-01',
      village: 'Uruli Kanchan',
      block: 'Haveli',
      district: 'Pune',
      state: 'Maharashtra',
    },
  },
  VETERINARIAN: {
    id: 'usr-vet-01',
    name: 'Dr. Aniket Kulkarni',
    email: 'vet@pashusetu.gov.in',
    mobile: '9822012345',
    role: 'VETERINARIAN',
    language: 'en',
    vetProfile: {
      id: 'vp-01',
      vetId: 'VET-MH-2024-042',
      qualification: 'B.V.Sc & A.H., M.V.Sc (Veterinary Medicine)',
      hospitalName: 'District Veterinary Polyclinic, Aundh, Pune',
      assignedDistrict: 'Pune',
      assignedBlock: 'Haveli',
    },
  },
  GOVERNMENT: {
    id: 'usr-govt-01',
    name: 'Dr. Sunita Deshmukh',
    email: 'admin@pashusetu.gov.in',
    mobile: '9422098765',
    role: 'GOVERNMENT',
    language: 'en',
    govtProfile: {
      id: 'gp-01',
      officialId: 'MAH-AHD-001',
      department: 'Department of Animal Husbandry, Govt of Maharashtra',
      designation: 'Joint Director (Disease Surveillance & Epidemiology)',
      jurisdiction: 'Maharashtra State',
    },
  },
};

export const FALLBACK_FARMER_STATS = {
  totalAnimals: 4,
  healthyAnimals: 2,
  sickAnimals: 1,
  underObservation: 1,
  activeReports: 2,
  vaccinationCoverage: 75,
};

export const FALLBACK_ANIMALS: Animal[] = [
  {
    id: 'c7b4112e-1111-4f81-80a1-cow000000001',
    farmerId: 'fp-01',
    animalCode: 'PS-COW-001',
    name: 'Gauri (गौरी)',
    species: 'Cow',
    breed: 'Gir',
    gender: 'Female',
    ageYears: 4.5,
    weightKg: 380,
    color: 'Reddish Brown',
    identificationNumber: 'TAG-MH-829101',
    healthStatus: 'SICK',
    photoUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&auto=format&fit=crop',
    village: 'Uruli Kanchan',
    block: 'Haveli',
    district: 'Pune',
    latitude: 18.4862,
    longitude: 74.1332,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    farmer: {
      village: 'Uruli Kanchan',
      block: 'Haveli',
      district: 'Pune',
      user: { name: 'Ramesh Tukaram Patil', mobile: '9876543210', email: 'farmer@pashusetu.gov.in' },
    },
  },
  {
    id: 'c7b4112e-2222-4f81-80a1-buf000000002',
    farmerId: 'fp-01',
    animalCode: 'PS-BUF-002',
    name: 'Lakshmi (लक्ष्मी)',
    species: 'Buffalo',
    breed: 'Murrah',
    gender: 'Female',
    ageYears: 5.0,
    weightKg: 520,
    color: 'Jet Black',
    identificationNumber: 'TAG-MH-829102',
    healthStatus: 'OBSERVATION',
    photoUrl: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?w=600&auto=format&fit=crop',
    village: 'Uruli Kanchan',
    block: 'Haveli',
    district: 'Pune',
    latitude: 18.4875,
    longitude: 74.1345,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    farmer: {
      village: 'Uruli Kanchan',
      block: 'Haveli',
      district: 'Pune',
      user: { name: 'Ramesh Tukaram Patil', mobile: '9876543210', email: 'farmer@pashusetu.gov.in' },
    },
  },
  {
    id: 'c7b4112e-3333-4f81-80a1-goa000000003',
    farmerId: 'fp-01',
    animalCode: 'PS-GOA-003',
    name: 'Kalu (काळू)',
    species: 'Goat',
    breed: 'Osmanabadi',
    gender: 'Male',
    ageYears: 2.0,
    weightKg: 38,
    color: 'Black',
    identificationNumber: 'TAG-MH-829103',
    healthStatus: 'HEALTHY',
    photoUrl: 'https://images.unsplash.com/photo-1524024973431-2ad916746881?w=600&auto=format&fit=crop',
    village: 'Uruli Kanchan',
    block: 'Haveli',
    district: 'Pune',
    latitude: 18.4851,
    longitude: 74.1321,
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    farmer: {
      village: 'Uruli Kanchan',
      block: 'Haveli',
      district: 'Pune',
      user: { name: 'Ramesh Tukaram Patil', mobile: '9876543210', email: 'farmer@pashusetu.gov.in' },
    },
  },
  {
    id: 'c7b4112e-4444-4f81-80a1-cow000000004',
    farmerId: 'fp-01',
    animalCode: 'PS-COW-004',
    name: 'Kapila (कपिला)',
    species: 'Cow',
    breed: 'Sahiwal',
    gender: 'Female',
    ageYears: 3.2,
    weightKg: 350,
    color: 'Pale Red',
    identificationNumber: 'TAG-MH-829104',
    healthStatus: 'HEALTHY',
    photoUrl: '/images/animals/kapila.jpg',
    village: 'Uruli Kanchan',
    block: 'Haveli',
    district: 'Pune',
    latitude: 18.4868,
    longitude: 74.1352,
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    farmer: {
      village: 'Uruli Kanchan',
      block: 'Haveli',
      district: 'Pune',
      user: { name: 'Ramesh Tukaram Patil', mobile: '9876543210', email: 'farmer@pashusetu.gov.in' },
    },
  },
];

export const FALLBACK_REPORTS: SymptomReport[] = [
  {
    id: 'rep-01',
    reportCode: 'REP-2026-0001',
    animalId: 'c7b4112e-1111-4f81-80a1-cow000000001',
    farmerId: 'usr-farmer-01',
    symptoms: JSON.stringify([
      'Fever',
      'Skin Lesions',
      'Weakness',
      'Reduced Milk Production',
      'Lameness',
    ]),
    durationDays: 3,
    severity: 'Severe',
    temperatureF: 104.2,
    appetiteStatus: 'None',
    milkProductionChange: 'Severe Drop',
    additionalDescription:
      'Cow is drooling continuously with blisters on tongue and dental pad. Limping severely on left foreleg. Milk production dropped from 14L to 3L.',
    village: 'Uruli Kanchan',
    block: 'Haveli',
    district: 'Pune',
    latitude: 18.4862,
    longitude: 74.1332,
    riskScore: 82,
    riskLevel: 'CRITICAL',
    status: 'DIAGNOSIS_AVAILABLE',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    animal: FALLBACK_ANIMALS[0],
    riskAssessment: {
      id: 'ra-01',
      reportId: 'rep-01',
      riskScore: 82,
      riskLevel: 'CRITICAL',
      possibleCategory: 'Foot and Mouth Disease (FMD) / लाळ खुरकूत',
      riskFactors: JSON.stringify([
        'Elevated body temperature / fever (+15)',
        'Excessive salivation / oral ulceration (+20)',
        'Locomotive impairment / hoof lesions (+15)',
        'Cutaneous lesions / vesicles present (+25)',
        'High fever reading (104.2°F) (+20)',
        'Complete anorexia (refusal to feed) (+12)',
        'Acute drop in milk yield (>50%) (+15)',
      ]),
      recommendedAction:
        'URGENT: Immediately isolate the affected animal away from the herd. Avoid community grazing or water troughs. Contact local Veterinary Officer immediately.',
      isDecisionSupportOnly: true,
      engineVersion: 'v1.0-rule-based',
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    diseaseCase: {
      id: 'case-01',
      caseCode: 'CASE-MH-2026-0001',
      reportId: 'rep-01',
      animalId: 'c7b4112e-1111-4f81-80a1-cow000000001',
      vetId: 'vp-01',
      suspectedDisease: 'Foot and Mouth Disease (FMD)',
      confirmedDisease: 'Foot and Mouth Disease (FMD) — Serotype O',
      clinicalDiagnosis: 'Acute Aphthous Fever (Foot and Mouth Disease) with secondary interdigital infection',
      clinicalSeverity: 'Critical',
      clinicalNotes: 'Physical examination confirmed rupture of vesicles on the dorsum of tongue and coronary band of left hooves. Body temp 104.1°F.',
      recommendedAction: 'Quarantine animal, symptomatic antipyretic therapy, antiseptic hoof wash twice daily.',
      status: 'DIAGNOSED',
      escalatedToGovt: true,
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      report: null as any,
    },
  },
  {
    id: 'rep-02',
    reportCode: 'REP-2026-0002',
    animalId: 'c7b4112e-2222-4f81-80a1-buf000000002',
    farmerId: 'usr-farmer-01',
    symptoms: JSON.stringify(['High Fever', 'Coughing / Respiratory Distress', 'Nasal Discharge']),
    durationDays: 2,
    severity: 'Moderate',
    temperatureF: 103.5,
    appetiteStatus: 'Reduced',
    milkProductionChange: 'Mild Drop',
    additionalDescription: 'Buffalo breathing heavily with serous nasal discharge and dullness.',
    village: 'Uruli Kanchan',
    block: 'Haveli',
    district: 'Pune',
    latitude: 18.4875,
    longitude: 74.1345,
    riskScore: 68,
    riskLevel: 'HIGH',
    status: 'UNDER_REVIEW',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    animal: FALLBACK_ANIMALS[1],
  },
];

export const FALLBACK_VACCINATIONS: Vaccination[] = [
  {
    id: 'vac-01',
    animalId: 'c7b4112e-1111-4f81-80a1-cow000000001',
    vaccineName: 'Foot and Mouth Disease (FMD)',
    batchNumber: 'FMD-MH-2025-08',
    doseNumber: 2,
    administeredDate: '2025-10-15',
    nextDueDate: '2026-04-15',
    administeredBy: 'Dr. Aniket Kulkarni',
    status: 'COMPLETED',
    notes: 'Biannual oil-adjuvant vaccine administered subcutaneously.',
    animal: FALLBACK_ANIMALS[0],
  },
  {
    id: 'vac-02',
    animalId: 'c7b4112e-1111-4f81-80a1-cow000000001',
    vaccineName: 'Haemorrhagic Septicaemia (HS)',
    batchNumber: 'HS-2025-41',
    doseNumber: 1,
    administeredDate: '2025-05-10',
    nextDueDate: '2026-05-10',
    administeredBy: 'Dr. Aniket Kulkarni',
    status: 'COMPLETED',
    animal: FALLBACK_ANIMALS[0],
  },
  {
    id: 'vac-03',
    animalId: 'c7b4112e-1111-4f81-80a1-cow000000001',
    vaccineName: 'Brucellosis',
    batchNumber: 'BRU-19-S',
    doseNumber: 1,
    administeredDate: '2024-02-10',
    status: 'COMPLETED',
    notes: 'Calfhood vaccination done.',
    animal: FALLBACK_ANIMALS[0],
  },
  {
    id: 'vac-04',
    animalId: 'c7b4112e-2222-4f81-80a1-buf000000002',
    vaccineName: 'Foot and Mouth Disease (FMD)',
    batchNumber: 'FMD-MH-2025-08',
    doseNumber: 1,
    administeredDate: '2025-10-15',
    nextDueDate: '2026-04-15',
    administeredBy: 'Dr. Aniket Kulkarni',
    status: 'COMPLETED',
    animal: FALLBACK_ANIMALS[1],
  },
  {
    id: 'vac-05',
    animalId: 'c7b4112e-2222-4f81-80a1-buf000000002',
    vaccineName: 'Black Quarter (BQ)',
    batchNumber: 'BQ-2025-12',
    doseNumber: 1,
    administeredDate: '2025-06-01',
    nextDueDate: '2026-06-01',
    administeredBy: 'Dr. Aniket Kulkarni',
    status: 'COMPLETED',
    animal: FALLBACK_ANIMALS[1],
  },
  {
    id: 'vac-06',
    animalId: 'c7b4112e-3333-4f81-80a1-goa000000003',
    vaccineName: 'PPR (Peste des Petits Ruminants)',
    batchNumber: 'PPR-VAC-09',
    doseNumber: 1,
    administeredDate: '2024-11-20',
    nextDueDate: '2027-11-20',
    status: 'COMPLETED',
    notes: 'Valid for 3 years immunity.',
    animal: FALLBACK_ANIMALS[2],
  },
];

export const FALLBACK_TREATMENTS: Treatment[] = [
  {
    id: 'trt-01',
    caseId: 'case-01',
    animalId: 'c7b4112e-1111-4f81-80a1-cow000000001',
    vetId: 'vp-01',
    diagnosis: 'Acute Foot and Mouth Disease',
    medicines: JSON.stringify([
      { name: 'Inj. Meloxicam with Paracetamol (Melonex Plus)', dosage: '15 ml', frequency: 'Once daily IM', duration: '3 days' },
      { name: 'Inj. Ceftiofur Sodium (Xyrofur)', dosage: '1 gram', frequency: 'Once daily IM', duration: '3 days' },
      { name: 'Boro-glycerine Liquid', dosage: 'Apply to oral lesions', frequency: '3 times daily', duration: '5 days' },
      { name: 'Potassium Permanganate (1:1000)', dosage: 'Hoof footbath', frequency: 'Twice daily', duration: '7 days' },
    ]),
    instructions: 'Feed soft green fodder and lukewarm rice gruel. Keep floor clean and dry with lime powder dusting.',
    startDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    followUpDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Follow up after 4 days to assess vesicle healing and feed intake.',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    animal: FALLBACK_ANIMALS[0],
    vet: {
      qualification: 'B.V.Sc & A.H., M.V.Sc (Veterinary Medicine)',
      hospitalName: 'District Veterinary Polyclinic, Aundh, Pune',
      user: { name: 'Dr. Aniket Kulkarni', mobile: '9822012345' },
    },
  },
];

export const FALLBACK_CASES: DiseaseCase[] = [
  {
    id: 'case-01',
    caseCode: 'CASE-MH-2026-0001',
    reportId: 'rep-01',
    animalId: 'c7b4112e-1111-4f81-80a1-cow000000001',
    vetId: 'vp-01',
    suspectedDisease: 'Foot and Mouth Disease (FMD)',
    confirmedDisease: 'Foot and Mouth Disease (FMD) — Serotype O',
    clinicalDiagnosis: 'Acute Aphthous Fever (Foot and Mouth Disease) with secondary interdigital infection',
    clinicalSeverity: 'Critical',
    clinicalNotes:
      'Physical examination confirmed rupture of vesicles on the dorsum of tongue and coronary band of left hooves. Body temp 104.1°F. Animal in severe pain. Immediate ring vaccination within 5 km radius requested.',
    recommendedAction: 'Quarantine animal, symptomatic antipyretic therapy, antiseptic hoof wash twice daily.',
    status: 'DIAGNOSED',
    escalatedToGovt: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    report: FALLBACK_REPORTS[0],
    animal: FALLBACK_ANIMALS[0],
    vet: {
      id: 'vp-01',
      vetId: 'VET-MH-2024-042',
      qualification: 'B.V.Sc & A.H., M.V.Sc (Veterinary Medicine)',
      hospitalName: 'District Veterinary Polyclinic, Aundh, Pune',
      user: { name: 'Dr. Aniket Kulkarni', mobile: '9822012345', email: 'vet@pashusetu.gov.in' },
    },
    treatments: FALLBACK_TREATMENTS,
  },
  {
    id: 'case-02',
    caseCode: 'CASE-MH-2026-0002',
    reportId: 'rep-02',
    animalId: 'c7b4112e-2222-4f81-80a1-buf000000002',
    vetId: 'vp-01',
    suspectedDisease: 'Haemorrhagic Septicaemia (HS)',
    clinicalDiagnosis: 'Suspected acute respiratory infection / early stage HS',
    clinicalSeverity: 'High',
    clinicalNotes: 'Submandibular swelling beginning to develop. Breathing laboured.',
    recommendedAction: 'Blood smear ordered for Pasteurella multocida identification. Broad spectrum parenteral antibiotics initiated.',
    status: 'UNDER_REVIEW',
    escalatedToGovt: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    report: FALLBACK_REPORTS[1],
    animal: FALLBACK_ANIMALS[1],
    vet: {
      id: 'vp-01',
      vetId: 'VET-MH-2024-042',
      qualification: 'B.V.Sc & A.H., M.V.Sc (Veterinary Medicine)',
      hospitalName: 'District Veterinary Polyclinic, Aundh, Pune',
      user: { name: 'Dr. Aniket Kulkarni', mobile: '9822012345', email: 'vet@pashusetu.gov.in' },
    },
  },
  {
    id: 'case-03',
    caseCode: 'CASE-MH-2026-0003',
    reportId: 'rep-03',
    animalId: 'c7b4112e-4444-4f81-80a1-cow000000004',
    vetId: 'vp-01',
    suspectedDisease: 'Lumpy Skin Disease (LSD)',
    confirmedDisease: 'Lumpy Skin Disease (LSD)',
    clinicalDiagnosis: 'Nodular cutaneous eruptions across neck, flank, and perineum. Mild pyrexia.',
    clinicalSeverity: 'High',
    clinicalNotes: 'Well circumscribed 2-4 cm firm skin nodules. Animal is stable but isolated.',
    recommendedAction: 'Apply fly repellent ointment, neem leaves fumigation, oral multivitamins and anti-inflammatory syrup.',
    status: 'TREATMENT_STARTED',
    escalatedToGovt: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    report: FALLBACK_REPORTS[0],
    animal: FALLBACK_ANIMALS[3],
    vet: {
      id: 'vp-01',
      vetId: 'VET-MH-2024-042',
      qualification: 'B.V.Sc & A.H., M.V.Sc (Veterinary Medicine)',
      hospitalName: 'District Veterinary Polyclinic, Aundh, Pune',
      user: { name: 'Dr. Aniket Kulkarni', mobile: '9822012345', email: 'vet@pashusetu.gov.in' },
    },
  },
];

export const FALLBACK_VET_STATS = {
  totalCases: 18,
  newCases: 4,
  pendingCases: 7,
  highRiskCases: 5,
  criticalCases: 3,
  resolvedCases: 11,
  pendingSamples: 2,
};

export const FALLBACK_LAB_SAMPLES: LabSample[] = [
  {
    id: 'smp-01',
    sampleCode: 'SMP-2026-0001',
    caseId: 'case-01',
    animalId: 'c7b4112e-1111-4f81-80a1-cow000000001',
    sampleType: 'Nasal Swab & Vesicular Fluid',
    collectedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    collectionLocation: 'Patil Farmstead, Uruli Kanchan',
    laboratoryName: 'Disease Investigation Section (DIS), Aundh, Pune',
    testType: 'RT-PCR',
    status: 'COMPLETED',
    result: 'POSITIVE',
    resultNotes: 'RT-PCR confirmed Foot and Mouth Disease virus Serotype O. Positive viral genome copy detected.',
    resultDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    animal: FALLBACK_ANIMALS[0],
  },
  {
    id: 'smp-02',
    sampleCode: 'SMP-2026-0002',
    caseId: 'case-02',
    animalId: 'c7b4112e-2222-4f81-80a1-buf000000002',
    sampleType: 'Blood Smear & Culture',
    collectedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    collectionLocation: 'Patil Farmstead, Uruli Kanchan',
    laboratoryName: 'Disease Investigation Section (DIS), Aundh, Pune',
    testType: 'Bipolar Staining & Culture',
    status: 'TESTING',
    animal: FALLBACK_ANIMALS[1],
  },
];

export const FALLBACK_GOVT_STATS = {
  totalRegisteredAnimals: 12840,
  activeCases: 46,
  suspectedOutbreaks: 3,
  confirmedOutbreaks: 2,
  animalMortality: 5,
  vaccinationCoverage: 84,
  activeVeterinaryResponses: 19,
};

export const FALLBACK_OUTBREAKS: Outbreak[] = [
  {
    id: 'out-01',
    outbreakCode: 'OUT-MH-2026-001',
    district: 'Pune',
    block: 'Haveli',
    village: 'Uruli Kanchan',
    latitude: 18.4862,
    longitude: 74.1332,
    suspectedDisease: 'Foot and Mouth Disease (FMD)',
    caseCount: 14,
    deathCount: 2,
    riskLevel: 'CRITICAL',
    status: 'CONTAINMENT_ACTIVE',
    assignedTeam: 'Pune District Mobile Veterinary Rapid Response Team #3',
    detectedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'out-02',
    outbreakCode: 'OUT-MH-2026-002',
    district: 'Ahmednagar',
    block: 'Rahata',
    village: 'Shirdi Rural',
    latitude: 19.7645,
    longitude: 74.4776,
    suspectedDisease: 'Lumpy Skin Disease (LSD)',
    caseCount: 8,
    deathCount: 0,
    riskLevel: 'HIGH',
    status: 'UNDER_INVESTIGATION',
    assignedTeam: 'Ahmednagar Mobile Unit #1',
    detectedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'out-03',
    outbreakCode: 'OUT-MH-2026-003',
    district: 'Satara',
    block: 'Karad',
    village: 'Ogalewadi',
    latitude: 17.2882,
    longitude: 74.1831,
    suspectedDisease: 'Black Quarter (BQ)',
    caseCount: 5,
    deathCount: 1,
    riskLevel: 'HIGH',
    status: 'RING_VACCINATION' as any,
    assignedTeam: 'Karad Polyclinic Rapid Action Team',
    detectedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const FALLBACK_GIS_DATA = {
  outbreaks: FALLBACK_OUTBREAKS,
  reports: [
    {
      id: 'gis-rep-1',
      reportCode: 'REP-2026-0001',
      village: 'Uruli Kanchan',
      block: 'Haveli',
      district: 'Pune',
      latitude: 18.4862,
      longitude: 74.1332,
      riskLevel: 'CRITICAL',
      riskScore: 82,
      status: 'DIAGNOSIS_AVAILABLE',
      createdAt: new Date().toISOString(),
      animal: { species: 'Cow', breed: 'Gir' },
    },
    {
      id: 'gis-rep-2',
      reportCode: 'REP-2026-0002',
      village: 'Uruli Kanchan',
      block: 'Haveli',
      district: 'Pune',
      latitude: 18.4875,
      longitude: 74.1345,
      riskLevel: 'HIGH',
      riskScore: 68,
      status: 'UNDER_REVIEW',
      animal: { species: 'Buffalo', breed: 'Murrah' },
    },
    {
      id: 'gis-rep-3',
      reportCode: 'REP-2026-0004',
      village: 'Loni Kalbhor',
      block: 'Haveli',
      district: 'Pune',
      latitude: 18.4905,
      longitude: 74.0211,
      riskLevel: 'HIGH',
      riskScore: 74,
      status: 'VET_ASSIGNED',
      animal: { species: 'Cow', breed: 'HF Crossbred' },
    },
    {
      id: 'gis-rep-4',
      reportCode: 'REP-2026-0005',
      village: 'Shirdi Rural',
      block: 'Rahata',
      district: 'Ahmednagar',
      latitude: 19.7645,
      longitude: 74.4776,
      riskLevel: 'HIGH',
      riskScore: 71,
      status: 'UNDER_REVIEW',
      animal: { species: 'Cow', breed: 'Gir' },
    },
    {
      id: 'gis-rep-5',
      reportCode: 'REP-2026-0006',
      village: 'Ogalewadi',
      block: 'Karad',
      district: 'Satara',
      latitude: 17.2882,
      longitude: 74.1831,
      riskLevel: 'HIGH',
      riskScore: 78,
      status: 'SAMPLE_REQUESTED',
      animal: { species: 'Buffalo', breed: 'Pandharpuri' },
    },
  ],
  districtLayers: [
    { district: 'Pune', lat: 18.5204, lng: 73.8567, activeCases: 19, animalDeaths: 2, riskLevel: 'CRITICAL' },
    { district: 'Satara', lat: 17.6805, lng: 74.0183, activeCases: 9, animalDeaths: 1, riskLevel: 'HIGH' },
    { district: 'Ahmednagar', lat: 19.0948, lng: 74.748, activeCases: 11, animalDeaths: 0, riskLevel: 'HIGH' },
    { district: 'Nashik', lat: 19.9975, lng: 73.7898, activeCases: 4, animalDeaths: 0, riskLevel: 'MEDIUM' },
    { district: 'Kolhapur', lat: 16.705, lng: 74.2433, activeCases: 2, animalDeaths: 0, riskLevel: 'LOW' },
    { district: 'Solapur', lat: 17.6599, lng: 75.9064, activeCases: 1, animalDeaths: 0, riskLevel: 'LOW' },
    { district: 'Sangli', lat: 16.8524, lng: 74.5815, activeCases: 0, animalDeaths: 0, riskLevel: 'LOW' },
    { district: 'Aurangabad', lat: 19.8762, lng: 75.3433, activeCases: 0, animalDeaths: 0, riskLevel: 'LOW' },
  ],
};

export const FALLBACK_ANALYTICS = {
  diseaseBreakdown: [
    { disease: 'Foot and Mouth Disease (FMD)', fullName: 'Foot and Mouth Disease (FMD)', cases: 18 },
    { disease: 'Lumpy Skin Disease (LSD)', fullName: 'Lumpy Skin Disease (LSD)', cases: 12 },
    { disease: 'Haemorrhagic Septicaemia (HS)', fullName: 'Haemorrhagic Septicaemia (HS)', cases: 9 },
    { disease: 'Black Quarter (BQ)', fullName: 'Black Quarter (BQ)', cases: 5 },
    { disease: 'Brucellosis', fullName: 'Brucellosis', cases: 2 },
  ],
  districtBreakdown: [
    { district: 'Pune', totalAnimals: 3840, cases: 19, deaths: 2, riskLevel: 'CRITICAL' },
    { district: 'Ahmednagar', totalAnimals: 2950, cases: 11, deaths: 0, riskLevel: 'HIGH' },
    { district: 'Satara', totalAnimals: 2410, cases: 9, deaths: 1, riskLevel: 'HIGH' },
    { district: 'Nashik', totalAnimals: 1820, cases: 4, deaths: 0, riskLevel: 'MEDIUM' },
    { district: 'Kolhapur', totalAnimals: 980, cases: 2, deaths: 0, riskLevel: 'LOW' },
    { district: 'Solapur', totalAnimals: 840, cases: 1, deaths: 0, riskLevel: 'LOW' },
  ],
  vaccinationByDistrict: [
    { district: 'Pune', totalAnimals: 3840, vaccinatedAnimals: 3340, coverageRate: 87 },
    { district: 'Satara', totalAnimals: 2410, vaccinatedAnimals: 2050, coverageRate: 85 },
    { district: 'Ahmednagar', totalAnimals: 2950, vaccinatedAnimals: 2360, coverageRate: 80 },
    { district: 'Nashik', totalAnimals: 1820, vaccinatedAnimals: 1510, coverageRate: 83 },
    { district: 'Kolhapur', totalAnimals: 980, vaccinatedAnimals: 890, coverageRate: 91 },
    { district: 'Solapur', totalAnimals: 840, vaccinatedAnimals: 690, coverageRate: 82 },
  ],
  responseMetrics: {
    totalVets: 18,
    assignedCases: 19,
    resolvedCases: 11,
    avgResponseHours: 3.8,
  },
};

export const FALLBACK_ADVISORIES: Advisory[] = [
  {
    id: 'adv-01',
    titleEn: 'Immediate Ring Vaccination & Biosecurity Advisory: FMD Outbreak in Haveli Block',
    titleMr: 'तातडीचे रिंग लसीकरण व जैवसुरक्षा सूचना: हवेली तालुक्यात लाळ खुरकूत प्रादुर्भाव',
    titleHi: 'तत्काल रिंग टीकाकरण व जैव सुरक्षा सलाह: हवेली ब्लॉक में एफएमडी प्रकोप',
    contentEn:
      'A confirmed cluster of Foot and Mouth Disease (FMD) Serotype O has been isolated in Uruli Kanchan and adjoining villages. All livestock owners within 5 km radius are directed to present cattle and buffaloes for mandatory ring vaccination. Restrict inter-village animal transport and close cattle markets until containment clearance.',
    contentMr:
      'उरुळी कांचन व लगतच्या गावांमध्ये लाळ खुरकूत (एफएमडी) सेरोटाइप ओ विषाणूचा प्रादुर्भाव आढळून आला आहे. ५ किमी परिसरातील सर्व पशुपालकांनी जनावरांचे रिंग लसीकरण करून घ्यावे. जनावरांची वाहतूक व बाजार तात्पुरते बंद ठेवण्यात येत आहेत.',
    contentHi:
      'उरुली कंचन में खुरपका-मुंहपका (FMD) सीरोटाइप O का प्रकोप दर्ज किया गया है। 5 किमी दायरे के सभी पशुपालक अनिवार्य टीकाकरण कराएं। मवेशियों का परिवहन स्थगित रखें।',
    targetDistrict: 'Pune',
    severity: 'URGENT',
    issuedBy: 'Joint Director of Animal Husbandry (Disease Surveillance), Pune Division',
    isActive: true,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'adv-02',
    titleEn: 'Seasonal Advisory: Preventive Immunization Against Haemorrhagic Septicaemia (HS)',
    titleMr: 'हंगामी सूचना: घटसर्प (एच.एस.) प्रतिबंधक लसीकरण मोहीम',
    titleHi: 'मौसमी सलाह: गलघोंटू (HS) रोग के विरुद्ध पूर्व-रोकथाम टीकाकरण',
    contentEn:
      'Ahead of monsoon showers, livestock farmers across Pune, Satara, and Ahmednagar are strongly urged to vaccinate cattle and buffaloes with the combined HS-BQ oil adjuvant vaccine. Report any sudden respiratory distress or high fever immediately to the 1962 helpline.',
    contentMr:
      'पावसाळ्यापूर्वी पुणे, सातारा व अहिल्यानगर (अहमदनगर) जिल्ह्यातील पशुपालकांनी जनावरांचे घटसर्प व फऱ्या प्रतिबंधक लसीकरण पूर्ण करावे. श्वास घेण्यास त्रास किंवा उच्च ताप आढळल्यास त्वरित १९६२ वर संपर्क साधावा.',
    contentHi:
      'मानसून से पूर्व सभी पशुपालक अपने मवेशियों को गलघोंटू (HS) का टीका अवश्य लगवाएं। किसी भी आपात लक्षण पर 1962 पर कॉल करें।',
    targetDistrict: 'ALL',
    severity: 'WARNING',
    issuedBy: 'Directorate of Animal Husbandry, Govt. of Maharashtra',
    isActive: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'adv-03',
    titleEn: 'Vector Control & Hygiene Protocol for Lumpy Skin Disease (LSD)',
    titleMr: 'लंपी त्वचा रोग नियंत्रणासाठी कीटक व डास निर्मूलन मार्गदर्शक सूचना',
    titleHi: 'लंपी त्वचा रोग रोकथाम हेतु मच्छर व मक्खी नियंत्रण दिशा-निर्देश',
    contentEn:
      'Farmers in Shirdi and Rahata blocks must ensure daily insecticide spraying in sheds and smoke fumigation using neem leaves to control biting flies and mosquitoes. Disinfect shed floors with sodium hypochlorite or lime powder.',
    contentMr:
      'गोठ्यांमध्ये डास व गोचीड नियंत्रणासाठी कडुनिंबाचा धूर करावा. गोठ्याची फरशी चुन्याच्या पावडरने निर्जंतुक ठेवावी.',
    contentHi:
      'पशुबाड़े में मक्खी व मच्छरों के नियंत्रण के लिए नीम की पत्तियों का धुआं करें तथा चूने का छिड़काव करें।',
    targetDistrict: 'Ahmednagar',
    severity: 'NORMAL',
    issuedBy: 'District Veterinary Polyclinic, Ahmednagar',
    isActive: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const FALLBACK_VET_SERVICES: VetServiceLocation[] = [
  {
    id: 'vet-loc-01',
    name: 'District Veterinary Polyclinic, Aundh',
    type: 'District Polyclinic',
    district: 'Pune',
    block: 'Haveli',
    village: 'Aundh',
    address: 'Survey No. 42, Near DIS Center, Aundh, Pune - 411007',
    contactPhone: '020-25881234 / 9822012345',
    latitude: 18.559,
    longitude: 73.8074,
    doctorInCharge: 'Dr. Aniket Kulkarni (Senior Veterinary Officer)',
    operatingHours: '24x7 Emergency Casualty & 9:00 AM - 5:00 PM OPD',
  },
  {
    id: 'vet-loc-02',
    name: 'Uruli Kanchan Government Veterinary Dispensary (Grade 1)',
    type: 'Taluka Dispensary',
    district: 'Pune',
    block: 'Haveli',
    village: 'Uruli Kanchan',
    address: 'Opposite Gram Panchayat Office, Uruli Kanchan, Haveli, Pune - 412202',
    contactPhone: '020-26922111 / 9823456789',
    latitude: 18.4862,
    longitude: 74.1332,
    doctorInCharge: 'Dr. Rajesh Deshpande (Live Stock Development Officer)',
    operatingHours: '8:30 AM - 4:30 PM (Mon-Sat)',
  },
  {
    id: 'vet-loc-03',
    name: 'Loni Kalbhor Veterinary Aid Center',
    type: 'Primary Aid Center',
    district: 'Pune',
    block: 'Haveli',
    village: 'Loni Kalbhor',
    address: 'Pune-Solapur Highway, Near Toll Plaza, Loni Kalbhor, Pune - 412201',
    contactPhone: '9422033445',
    latitude: 18.4905,
    longitude: 74.0211,
    doctorInCharge: 'Dr. Sneha Jadhav (Veterinary Assistant)',
    operatingHours: '9:00 AM - 2:00 PM',
  },
  {
    id: 'vet-loc-04',
    name: 'Maharashtra Mobile Veterinary Clinic (MVU) Unit #3',
    type: 'Mobile Clinic (1962)',
    district: 'Pune',
    block: 'Haveli & Daund',
    village: 'Haveli Sub-division',
    address: 'Dispatched from Central Polyclinic, Pune',
    contactPhone: 'Toll-Free 1962',
    latitude: 18.5204,
    longitude: 73.8567,
    doctorInCharge: 'Rapid Response Medical Team #3',
    operatingHours: '24 Hours Emergency Dispatch on Dial 1962',
  },
];

export const FALLBACK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-01',
    userId: 'usr-farmer-01',
    title: '🚨 CRITICAL: Foot and Mouth Disease Outbreak Cluster',
    message: 'Urgent FMD cluster detected in Haveli block (Uruli Kanchan). Quarantine sick livestock and accept mandatory ring vaccination.',
    type: 'OUTBREAK',
    isRead: false,
    link: '/farmer/alerts',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-02',
    userId: 'usr-farmer-01',
    title: '📋 Veterinary Diagnosis Available for Gauri (Gir Cow)',
    message: 'Dr. Aniket Kulkarni has completed diagnosis: Acute Foot and Mouth Disease. View prescribed medicines and treatment schedule.',
    type: 'CASE_UPDATE',
    isRead: false,
    link: '/farmer/reports',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-03',
    userId: 'usr-farmer-01',
    title: '💉 Booster Vaccination Due Reminder',
    message: 'Lakshmi (Murrah Buffalo) is due for biannual FMD booster dose on 15-Apr-2026.',
    type: 'VACCINE',
    isRead: false,
    link: '/farmer/vaccinations',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-04',
    userId: 'usr-vet-01',
    title: '🔬 Lab Sample Confirmed POSITIVE (SMP-2026-0001)',
    message: 'DIS Aundh confirmed RT-PCR positive for FMD Serotype O in Cow Gauri. Outbreak protocol initiated.',
    type: 'ALERT',
    isRead: false,
    link: '/veterinarian/cases',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-05',
    userId: 'usr-govt-01',
    title: '🌐 Outbreak Containment Zone Activated',
    message: 'Haveli block FMD containment perimeter established. Mobile Rapid Response Unit #3 deployed.',
    type: 'OUTBREAK',
    isRead: true,
    link: '/government/outbreaks',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
];
